version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/bodytracker
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  frontend:
    build: ./frontend
    ports:
      - "5173:4173"
    depends_on:
      - backend

volumes:
  mongo_data:
